### ISSUE TITLE
"@retrurn" in method TYPO3Fluid DebugViewHelper breaks application

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#1756]
### Description

With your 4.3.18 release our applications broke because of the following error:

```
[Semantical Error] The annotation "@retrurn" in method TYPO3Fluid\Fluid\ViewHelpers\DebugViewHelper::getValuesOfNonScalarVariable() was never imported.
Did you maybe forget to add a "use" statement for this annotation?

  Type: Doctrine\Common\Annotations\AnnotationException
  File: Packages/Libraries/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php
  Line: 54

  Type: Neos\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
  Line: 641

Open Data/Logs/Exceptions/20190904081436926fb0.txt for a full stack trace.
```

Your package neos/fluid-adaptor requires "typo3fluid/fluid": "~2.1.3". The above mentioned annotation is wrong since version 1.1.0 and was fixed for version 2.3.0 (with https://github.com/TYPO3/Fluid/pull/260).

To be honest I do not know where exactly the problem is, but I’ve figured out that it occurs when updating all the Neos packages from version 4.3.17 to 4.3.18.

### Affected Versions

Neos:

Flow: 4.3.18

**Comment by kdambekalns** [comment]
The dependency on `typo3fluid/fluid` has not changed between 4.3.17 and 4.3.18.

- It should install 2.1.4, as shown by https://semver.mwl.be/#!?package=typo3fluid%2Ffluid&version=~2.1.3&minimum-stability=stable
- `composer create-project --keep-vcs neos/flow-base-distribution flow4318 4.3.18` installs 2.1.4 as expected
- On Travis CI, though, 2.4.1 is installed, see https://travis-ci.org/neos/flow-development-collection/jobs/579966948

Anyway, I can reproduce this. So something else has changed, so we now see the effect of that broken annotation.

**Comment by kdambekalns** [comment]
The error is gone when switching `neos/flow` from 4.3.18 to 4.3.17, and this is the cause: https://github.com/neos/flow-development-collection/pull/1637

**Comment by kdambekalns** [comment]
@albe Would you take care of this?

**Comment by MCStreetguy** [comment]
@kdambekalns Thanks a lot for providing a quick solution, some of our customers are affected and I only found the mentioned pull request when I googled the problem. It works just fine.

**Comment by kdambekalns** [comment]
So, it _should_ be a newer `typo3fluid/fluid` since https://github.com/neos/flow-development-collection/pull/1638 was merged. But that was only half-baked. 😬

**Comment by kdambekalns** [comment]
That should fix it.

**Comment by kaystrobach** [comment]
will there be a new flow release containing the fix?

**Comment by kdambekalns** [comment]
Well, yes, of course. Why shouldn't there be?

**Comment by kaystrobach** [comment]
just asking - was not clear to me. so i will force a downgrade to 4.3.17 for now to avoid the problem

**Comment by albe** [comment]
Sorry that the supposed fix didn't really fix because I still after all these years can't properly change dependency versions 🤦‍♂

Fixing the dependency version requirement should fix the issue, by installing a newer Fluid version. I'm stumbled though as to why it would break suddenly when switching from 4.3.17 to 4.3.18, because nothing in that regard has changed.

My assumed explanation would be, that before the switch, Fluid was still installed in a version that did not contain the broken annotation, and the update to Neos 4.3.18 just triggered a minor update of Fluid that contained the broken annotation.

Anyway, downgrading shouldn't solve the issue really, if it does, something is bogus and I'd like to investigate :)

**Comment by kdambekalns** [comment]
@albe Why? Because…

> and this is the cause: #1637

**Comment by kaystrobach** [comment]
this are the installed versions. annotations are ignored in flow prior to 4.3.18 in fluid - right?

``` 
neos/fluid-adaptor                             4.3.18               Fluid Templating Framework Adaptor
typo3fluid/fluid                               2.1.4                The TYPO3 Fluid template rendering engine
neos/flow                                      4.3.17               Flow Application Framework
neos/flow-log                                  4.3.18               Flow Framework Logger
```

**Comment by kdambekalns** [comment]
> annotations are ignored in flow prior to 4.3.18 in fluid - right?

Well, to be precise: reflection was enabled for typo3fluid/fluid in 4.3.18, that's the cause.

**Comment by albe** [comment]
Ah, yes, now I get it. Du'h. And now I remember also seeing this error when trying to enable reflection for Fluid. It's maybe still too early? Dunno 😲

**Comment by kitsunet** [comment]
This makes me realise we might rethink this decision and find another way, because now we are dependent on the correctness and usage of only "known" tags in fluid...

**Comment by kdambekalns** [comment]
> now we are dependent on the correctness and usage of only "known" tags in fluid...

Huh? We always depend on that… also for other dependencies (partly). I guess we need to live with that. Or what would you do different?

(I was confused for a second, but you meant "tags" as in "annotations", not "git"…)

**Comment by kitsunet** [comment]
Sorry yes, our reflection somewhere makes a difference between annotations (Flow\Inject) and tags (return). :D 
Anyway, since a couple of versions of Flow any non Flow/Neos packages (based on composer package type) is not reflected (which is why the change added fluid back in). So we were pretty much in control of all places that could cause problems.

**Comment by albe** [comment]
True, but I think in regard to Fluid as it is still such a core dependency (previous internal feature), we should make this work correctly. I'm just a bit stumbled right now, about the release policy currently in Fluid - the commit that introduced that wrong annotation (tag) is here:
https://github.com/TYPO3/Fluid/commit/5acd2e9cc8944de2de7773f0b9eabf7a17669cba#diff-0c69e009acadacc13b46e0c3ee7c4c53

And apparently, it lives in all versions back to 1.1.0, while the fix for the wrong annotation (tag) only lives in 2.3.x upwards.

**Comment by albe** [comment]
Addendum (from discussion in Slack with Robin and Ferdinand):
Since the change in includeClasses won't work together with any Fluid version < 2.3, maybe we even need to change the version constraint to `>=2.3.0,<2.5.0`, even though that's not semver - but the supposed reflection fix is also breaking like that already.
The other option would be to revert the reflection change for 4.3 (only), since 5.0 already depends on a high enough version of Fluid.

@kdambekalns @kitsunet ?

**Comment by kdambekalns** [comment]
Reverting that for 4.3 would be an option for me.

**Comment by kitsunet** [comment]
Sure! Totally fine for me

**Comment by rkrahnen** [comment]
When do you think you can provide a version `4.3.19` with the reverted reflection change?

**Comment by albe** [comment]
PR with the revert is above and a release 4.3.19 has been tagged and should fix the bug.
