### ISSUE TITLE
Proxys for final methods should not be generated

### ISSUE THREAD

**Issue by hhoechtl** [neos/flow-development-collection#516]
Flow 3.3.3 generates a corrupt proxy object for `JsonArrayType`:

As `JsonArrayType` inherits from `Doctrine\DBAL\Types\JsonArrayType` which has a final constructor, this proxy class is invalid and causes the error: 

```
PHP Fatal error:  Cannot override final method Doctrine\DBAL\Types\Type::__construct() in /opt/tmp/Development/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_DataTypes_JsonArrayType.php on line 235
Fatal error: Cannot override final method
Doctrine\DBAL\Types\Type::__construct() in
/opt/tmp/Development/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_DataTypes_JsonArrayType.php
on line 235
```

```
use Doctrine\ORM\Mapping as ORM;
use TYPO3\Flow\Annotations as Flow;

/**
 * Extends the default doctrine JsonArrayType to work with entities.
 *
 * TOOD: If doctrine supports a Postgres 9.4 platform we could default to jsonb.
 */
class JsonArrayType extends JsonArrayType_Original implements \TYPO3\Flow\Object\Proxy\ProxyInterface {

    use \TYPO3\Flow\Object\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (method_exists(get_parent_class(), 'Flow_Aop_Proxy_buildMethodsAndAdvicesArray') && is_callable('parent::Flow_Aop_Proxy_buildMethodsAndAdvicesArray')) parent::Flow_Aop_Proxy_buildMethodsAndAdvicesArray();
        parent::__construct();
    }
```

**Comment by albe** [comment]
Hmmm, that but that's not something that changed in Doctrine lately, so that should have failed before, no? Are you in any way AOPing the DBAL types?

Anyway, the DBAL Types should be `Proxy(false)`, so yeah, should be fixed...

**Comment by hhoechtl** [comment]
FormBuilder is causing this proxies to contain the __construct which is wrong. No idea yet why, but removing formbuilder fixed it for the moment

**Comment by mkuiphuis** [comment]
Hans, great that you mentioned FormBuilder. I'm guessing you use the FormBuilderBundle from SimplyAdmire? There is a bug in the Policy.yaml file of that package. I have already created a PR for this bug in that package, but no replies yet. The fix is easy though:

if you change line 5 of the Policy.yaml file from:
```
matcher: 'method((TYPO3\FormBuilder\Controller\StandardController|SimplyAdmire\Neos\FormBuilderBundle\Controller\FormController)->.*Action())'
```
into
```
matcher: 'method(TYPO3\FormBuilder\Controller\StandardController|SimplyAdmire\Neos\FormBuilderBundle\Controller\FormController->.*Action())'
```
the problem should disappear....

It already has haunted some people on Slack

**Comment by kitsunet** [comment]
This issue is not entirely fixed, it describes a symptom of a prolbem that can happen with other classes as well. That we declared proxy false on our DataType is merely fixing that symptom, but the root cause must be fixed.

**Comment by bwaidelich** [comment]
FYI: There'll be a fix for this with #649 (I'm adding tests atm) and with Flow 4.0+ it might even be [allowed to proxy final methods](https://github.com/bwaidelich/flow-development-collection/commit/10d17b921e2979d31ed6269735b15d51dce4007c)
@mkuiphuis awesome catch, I would have searched for hours

**Comment by mkuiphuis** [comment]
@bwaidelich thanks, but all credit should go to @kitsunet as it took me hours that day until Christian was able to steer me in the right direction that a Policy.yaml had to be the culprit.

**Comment by bwaidelich** [comment]
> all credit should go to @kitsunet

OK, in that case I'm a little less impressed. After all he's Mister Proxy 😄

**Comment by kitsunet** [comment]
Can we probably close this?

**Comment by hhoechtl** [comment]
Yes, the matcher has already been changed in the FormBuilder and as it's changed in Flow 4.0+, I think this can be closed.
